### PR TITLE
create a bin packing benchmark

### PR DESCRIPTION
**Pull request by alejomonbar**
Recently, I added the bin Packing application and I would like to include the benchmark for this application. Owe to the inequality constraints, the problem becomes expensive after 3 items and does not converge for time_grover.

### CODE REVIEW

**Comment by t-imamichi** [comment]
`time_grover` fails in my environment as follows. Could you tune `num_value_qubits` so that it does not fail?
```
[ 75.00%] ··· binpacking.BinPackingBenchmarks.time_grover                                                                                   1/6 failed
[ 75.00%] ··· ================= ============ ============ =========
              --                             max_weight            
              ----------------- -----------------------------------
               number of items       2            4           8    
              ================= ============ ============ =========
                      2           103±3ms      115±1ms     134±3ms 
                      3          7.45±0.01s   25.6±0.04s    failed 
              ================= ============ ============ =========
```

**Comment by t-imamichi** [comment]
I tested it with the new version of qiskit and time_grover still fails. Could you check it?

```
[ 75.00%] ··· binpacking.BinPackingBenchmarks.time_grover                                                                         1/6 failed
[ 75.00%] ··· ================= ============ =========== =========
              --                            max_weight
              ----------------- ----------------------------------
               number of items       2            4          6
              ================= ============ =========== =========
                      2          118±0.6ms     137±7ms    132±5ms
                      3          6.83±0.07s   22.9±0.2s    failed
              ================= ============ =========== =========
```

**Comment by dlasecki** [comment]
Hello. What is the status of this contribution?

**Comment by t-imamichi** [comment]
I close this because no response for a long time.

**Pull request closed without merging**
